### ISSUE TITLE
Energy multiplier

### ISSUE THREAD

**Issue by Koudy86** [leandrotoledo/python-pzem#2]
Hi, 
I think, there is wrong multiplier on item Energy - on line 30 - there is multiplier=10, but I think according the manual, basic multiplier is 1; 10 is only, when Total energy ≥10kWh.
https://github.com/leandrotoledo/python-pzem/blob/main/pzem/pzem.py#L30

**Comment by leandrotoledo** [comment]
Sorry this took so long! Thanks for reporting the issue.

**Comment by Koudy86** [comment]
No problem ;)  Thank you for fixing.
